# Generated by Django 5.2.11 on 2026-05-17 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('page_access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_config', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_account_id', models.CharField(max_length=255, unique=True)),
                ('page_id', models.CharField(blank=True, max_length=255)),
                ('page_access_token', models.TextField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_config', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('business_account_id', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='bots.bot')),
            ],
        ),
    ]
