# Generated by Django 5.2.11 on 2026-05-17 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tenant_user_full_name_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('business_context', models.TextField(blank=True, help_text='Describe what your business does — the bot will use this as its persona.')),
                ('widget_enabled', models.BooleanField(default=True)),
                ('messages_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.TextField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='bots.bot')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header_text', models.CharField(default='Chat with us', max_length=255)),
                ('welcome_message', models.TextField(default='Hi! How can I help you today?')),
                ('predefined_questions', models.JSONField(blank=True, default=list, help_text='List of pre-filled questions shown in the widget.')),
                ('input_placeholder', models.CharField(default='Type a message...', max_length=255)),
                ('theme_color', models.CharField(default='#5B21B6', max_length=20)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('widget_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('widget_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('border_radius', models.PositiveIntegerField(default=12)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='bots/logos/')),
                ('widget_icon', models.ImageField(blank=True, null=True, upload_to='bots/icons/')),
                ('remove_branding', models.BooleanField(default=False)),
                ('enable_pulsing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='bots.bot')),
            ],
        ),
    ]
